#!/bin/sh

PKG=eeepc-acpi-scripts

set -e

case "$1" in
    upgrade|failed-upgrade|abort-install|abort-upgrade|remove|disappear)
        invoke-rc.d acpid restart>/dev/null
    ;;

    purge)
        invoke-rc.d acpid restart>/dev/null
        rm -f /var/lib/eeepc-acpi-scripts/cpufv
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0

