#!/bin/sh

set -e

# Prepare to move a conffile without triggering a dpkg question
prep_mv_conffile() {
    CONFFILE="$1"

    if [ -e "$CONFFILE" ]; then
        md5sum="`md5sum \"$CONFFILE\" | sed -e \"s/ .*//\"`"
        old_md5sum="`dpkg-query -W -f='${Conffiles}' eeepc-acpi-scripts | sed -n -e \"\\\\' $CONFFILE '{s/ obsolete$//;s/.* //p}\"`"
        if [ "$md5sum" = "$old_md5sum" ]; then
            rm -f "$CONFFILE"
        fi
    fi
}

case "$1" in
    install|upgrade)
        if dpkg --compare-versions "$2" le "1.0.11"; then
            prep_mv_conffile "/etc/modprobe.d/eeepc"
        fi
        if dpkg --compare-versions "$2" le "1.1.10"; then
            prep_mv_conffile "/etc/acpi/events/ac_adapter_inserted"
            prep_mv_conffile "/etc/acpi/events/ac_adapter_removed"
            prep_mv_conffile "/etc/acpi/events/hotkey"
            prep_mv_conffile "/etc/acpi/events/hotkey-button"
            prep_mv_conffile "/etc/acpi/events/hotkey-netlink"
            prep_mv_conffile "/etc/acpi/events/hotkey-video"
            prep_mv_conffile "/etc/acpi/events/lid"
            prep_mv_conffile "/etc/acpi/events/sleep"
            prep_mv_conffile "/etc/acpi/events/sleep-netlink"
            prep_mv_conffile "/etc/acpi/actions/ac_adapter.sh"
            prep_mv_conffile "/etc/acpi/actions/gsm.sh"
            prep_mv_conffile "/etc/acpi/actions/hotkey.sh"
            prep_mv_conffile "/etc/acpi/actions/lid.sh"
            prep_mv_conffile "/etc/acpi/actions/sleep.sh"
            prep_mv_conffile "/etc/acpi/actions/suspend.sh"
            prep_mv_conffile "/etc/acpi/actions/vga-toggle.sh"
            prep_mv_conffile "/etc/acpi/actions/volume.sh"
            prep_mv_conffile "/etc/acpi/actions/wireless.sh"
            prep_mv_conffile "/etc/acpi/lib/bluetooth.sh"
            prep_mv_conffile "/etc/acpi/lib/camera.sh"
            prep_mv_conffile "/etc/acpi/lib/eeepc-amixer-blacklist"
            prep_mv_conffile "/etc/acpi/lib/notify.sh"
            prep_mv_conffile "/etc/acpi/lib/shengine.sh"
            prep_mv_conffile "/etc/acpi/lib/sound.sh"
            prep_mv_conffile "/etc/acpi/lib/touchpad.sh"
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

