#!/bin/sh

set -e

# Prepare to move a conffile without triggering a dpkg question
prep_mv_conffile() {
    CONFFILE="$1"

    if [ -e "$CONFFILE" ]; then
        md5sum="`md5sum \"$CONFFILE\" | sed -e \"s/ .*//\"`"
        old_md5sum="`dpkg-query -W -f='${Conffiles}' eeepc-acpi-scripts | sed -n -e \"\\\\' $CONFFILE '{s/ obsolete$//;s/.* //p}\"`"
        if [ "$md5sum" = "$old_md5sum" ]; then
            rm -f "$CONFFILE"
        fi
    fi
}

case "$1" in
    install|upgrade)
        if dpkg --compare-versions "$2" le "1.0.11"; then
            prep_mv_conffile "/etc/modprobe.d/eeepc"
        fi
        if dpkg --compare-versions "$2" le "1.1.10"; then
            prep_mv_conffile "/etc/acpi/events/ac_adapter_inserted"
            prep_mv_conffile "/etc/acpi/events/ac_adapter_removed"
            prep_mv_conffile "/etc/acpi/actions/ac_adapter.sh"
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

